services:
  craftbox:
    build: .
    container_name: craftbox
    restart: unless-stopped
    ports:
      - "6464:6464"     # Web panel
      - "25565:25565"   # Default Minecraft server port
      # Add more ports as needed for additional servers:
      # - "25566:25566"
      # - "25567:25567"
    volumes:
      - craftbox-data:/app/data
    environment:
      - LOG_LEVEL=INFO
      # - NODE_ENV=production # Will require HTTPS for secure cookies, so only enable if you have a reverse proxy with SSL
      # - PORT=6464 # Change if you want to run the web panel on a different port
    stop_grace_period: 45s

volumes:
  craftbox-data:
