const fs = require('fs');
const path = require('path');

const DEFAULT_PROPERTIES = {
    'server-port': 25565,
    'gamemode': 'survival',
    'difficulty': 'easy',
    'max-players': 20,
    'motd': 'A Minecraft Server',
    'online-mode': true,
    'pvp': true,
    'spawn-protection': 16,
    'view-distance': 10,
    'enable-command-block': false,
    'allow-flight': false,
    'level-name': 'world',
    'level-seed': '',
    'white-list': false,
    'enforce-whitelist': false,
    'spawn-npcs': true,
    'spawn-animals': true,
    'spawn-monsters': true,
    'generate-structures': true,
    'enable-query': false,
    'enable-rcon': false,
    'enable-status': true,
    'sync-chunk-writes': true,
    'simulation-distance': 10,
    'max-tick-time': 60000,
    'max-world-size': 29999984,
    'network-compression-threshold': 256,
    'rate-limit': 0,
    'entity-broadcast-range-percentage': 100
};

/**
 * Write a server.properties file to the given directory.
 * @param {string} serverDir - Path to the server directory
 * @param {object} overrides - Properties to override defaults
 */
function writeServerProperties(serverDir, overrides = {}) {
    const props = { ...DEFAULT_PROPERTIES };

    // Apply overrides (camelCase keys mapped to kebab-case)
    if (overrides.serverPort !== undefined) props['server-port'] = overrides.serverPort;
    if (overrides.maxPlayers !== undefined) props['max-players'] = overrides.maxPlayers;
    if (overrides.motd !== undefined) props['motd'] = overrides.motd;
    if (overrides.gamemode !== undefined) props['gamemode'] = overrides.gamemode;
    if (overrides.difficulty !== undefined) props['difficulty'] = overrides.difficulty;
    if (overrides.viewDistance !== undefined) props['view-distance'] = overrides.viewDistance;
    if (overrides.levelSeed !== undefined) props['level-seed'] = overrides.levelSeed;

    // Allow raw property overrides
    Object.entries(overrides).forEach(([key, value]) => {
        if (key.includes('-')) props[key] = value;
    });

    const lines = ['#Minecraft server properties', `#Generated by Craftbox on ${new Date().toISOString()}`];
    for (const [key, value] of Object.entries(props)) {
        lines.push(`${key}=${value}`);
    }

    fs.writeFileSync(path.join(serverDir, 'server.properties'), lines.join('\n') + '\n');
}

/**
 * Write eula.txt with eula=true.
 * @param {string} serverDir - Path to the server directory
 */
function writeEula(serverDir) {
    const content = [
        '#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).',
        `#${new Date().toISOString()}`,
        'eula=true'
    ].join('\n') + '\n';

    fs.writeFileSync(path.join(serverDir, 'eula.txt'), content);
}

module.exports = { writeServerProperties, writeEula, DEFAULT_PROPERTIES };
