const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {
    writeServerProperties, writeEula, parseServerProperties, updateServerProperties, DEFAULT_PROPERTIES, modeNameOf
} = require('../../src/mc/serverProperties');
const { PROPERTY_META } = require('../../src/mc/propertyMeta');

function tempDir(t) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'craftbox-props-'));
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
    return dir;
}

const read = (dir) => fs.readFileSync(path.join(dir, 'server.properties'), 'utf8');
const write = (dir, content) => fs.writeFileSync(path.join(dir, 'server.properties'), content);

// The keys of a written file, in order, ignoring comments
const keysOf = (content) => content.split('\n')
    .filter((l) => l && !l.startsWith('#'))
    .map((l) => l.slice(0, l.indexOf('=')));

test('parse undoes the escapes Minecraft writes and tolerates spacing', (t) => {
    const dir = tempDir(t);
    write(dir, [
        '#Minecraft server properties',
        '#Mon Sep 28 12:00:00 BST 2026',
        'level-type=minecraft\\:flat',
        'motd=A \\= sign',
        'max-players = 7',
        'spawn-protection =16',
        'level-seed=',
        '',
        'not a property',
        'generator-settings={"a"\\:1}',
        ''
    ].join('\r\n'));
    assert.deepEqual(parseServerProperties(dir), {
        'level-type': 'minecraft:flat',
        'motd': 'A = sign',
        'max-players': '7',
        'spawn-protection': '16',
        'level-seed': '',
        'generator-settings': '{"a":1}'
    });
});

test('parse returns an empty object when there is no file', (t) => {
    assert.deepEqual(parseServerProperties(tempDir(t)), {});
});

test('a new file has the defaults, with first-start settings after the seed', (t) => {
    const dir = tempDir(t);
    writeServerProperties(dir, {}, { version: '1.21.1' });
    const content = read(dir);
    assert.match(content, /^#Minecraft server properties\n#Generated by Craftbox on /);
    const keys = keysOf(content);
    const seed = keys.indexOf('level-seed');
    assert.deepEqual(keys.slice(seed, seed + 6), [
        'level-seed', 'hardcore', 'level-type', 'generator-settings', 'initial-enabled-packs', 'initial-disabled-packs'
    ]);
    const props = parseServerProperties(dir);
    assert.equal(props.difficulty, 'normal');
    assert.equal(props.gamemode, 'survival');
    assert.equal(props['online-mode'], 'true');
    assert.equal(props['level-type'], 'minecraft:normal');
    assert.equal(props['generator-settings'], '{}');
    for (const key of Object.keys(DEFAULT_PROPERTIES)) assert.ok(key in props, `${key} missing`);
});

test('first-start settings follow the version', (t) => {
    const cases = {
        '1.12.2': { 'level-type': 'default', 'generator-settings': '', packs: false },
        '1.16.5': { 'level-type': 'default', 'generator-settings': '', packs: false },
        '1.18.2': { 'level-type': 'default', 'generator-settings': '{}', packs: false },
        '1.19.2': { 'level-type': 'minecraft:normal', 'generator-settings': '{}', packs: false },
        '1.19.3': { 'level-type': 'minecraft:normal', 'generator-settings': '{}', packs: true },
        '26.1': { 'level-type': 'minecraft:normal', 'generator-settings': '{}', packs: true },
        '': { 'level-type': 'minecraft:normal', 'generator-settings': '{}', packs: true } // a custom jar
    };
    for (const [version, want] of Object.entries(cases)) {
        const dir = tempDir(t);
        writeServerProperties(dir, {}, { version });
        const props = parseServerProperties(dir);
        assert.equal(props['level-type'], want['level-type'], `${version} level-type`);
        assert.equal(props['generator-settings'], want['generator-settings'], `${version} generator-settings`);
        assert.equal(props.hardcore, 'false', `${version} hardcore`);
        assert.equal('initial-enabled-packs' in props, want.packs, `${version} initial-enabled-packs`);
    }
});

test('overrides take camelCase and raw keys', (t) => {
    const dir = tempDir(t);
    writeServerProperties(dir, {
        serverPort: 25570, maxPlayers: 5, motd: 'Hi', gamemode: 'creative', difficulty: 'hard',
        viewDistance: 6, levelSeed: '1234', levelType: 'minecraft:flat',
        'enable-rcon': true, 'rcon.password': 'secret', notAProperty: 'x'
    }, { version: '1.21.1' });
    const props = parseServerProperties(dir);
    assert.equal(props['server-port'], '25570');
    assert.equal(props['max-players'], '5');
    assert.equal(props.motd, 'Hi');
    assert.equal(props.gamemode, 'creative');
    assert.equal(props.difficulty, 'hard');
    assert.equal(props['view-distance'], '6');
    assert.equal(props['level-seed'], '1234');
    assert.equal(props['level-type'], 'minecraft:flat');
    assert.equal(props['enable-rcon'], 'true');
    assert.equal(props['rcon.password'], 'secret');
    assert.ok(!('notAProperty' in props));
});

test('merging keeps an existing file line for line and only fills the gaps', (t) => {
    const dir = tempDir(t);
    write(dir, [
        '#From a modpack',
        'level-type=minecraft\\:amplified',
        'motd=\\u00A7aHello',
        'allow-flight=true',
        'server-port=1234',
        ''
    ].join('\n'));
    writeServerProperties(dir, { serverPort: 25570 }, { mergeExisting: true, version: '1.21.1' });
    const lines = read(dir).split('\n');
    assert.deepEqual(lines.slice(0, 5), [
        '#From a modpack',
        'level-type=minecraft\\:amplified',
        'motd=\\u00A7aHello',
        'allow-flight=true',
        'server-port=25570'
    ]);
    assert.equal(lines.at(-1), '', 'trailing newline kept');
    const props = parseServerProperties(dir);
    assert.equal(props['online-mode'], 'true', 'missing default filled in');
    assert.equal(props.hardcore, 'false', 'missing first-start setting filled in');
    assert.equal(lines.filter((l) => l.startsWith('level-type=')).length, 1, 'level-type duplicated');
});

test('merging with no existing file writes a fresh one', (t) => {
    const dir = tempDir(t);
    writeServerProperties(dir, { serverPort: 25571 }, { mergeExisting: true, version: '1.21.1' });
    assert.match(read(dir), /^#Minecraft server properties/);
    assert.equal(parseServerProperties(dir)['server-port'], '25571');
});

test('update edits in place, keeps comments and appends new keys', (t) => {
    const dir = tempDir(t);
    write(dir, '#comment\na=1\nb = 2\n\nc=3\n');
    updateServerProperties(dir, { b: 20, d: 4 });
    assert.equal(read(dir), '#comment\na=1\nb=20\n\nc=3\nd=4\n');
});

test('update keeps a file without a trailing newline that way', (t) => {
    const dir = tempDir(t);
    write(dir, 'a=1');
    updateServerProperties(dir, { b: 2 });
    assert.equal(read(dir), 'a=1\nb=2');
});

test('update does nothing when there is no file', (t) => {
    const dir = tempDir(t);
    updateServerProperties(dir, { a: 1 });
    assert.equal(fs.existsSync(path.join(dir, 'server.properties')), false);
});

// Before 1.14 Minecraft can't read a game mode or difficulty name: it plays
// Survival on Easy and rewrites the file with those numbers
test('game mode and difficulty are written as numbers before 1.14', (t) => {
    const modes = (dir) => { const p = parseServerProperties(dir); return `${p.gamemode} ${p.difficulty}`; };
    const cases = {
        '1.8.9': '1 3', '1.12.2': '1 3', '1.13.2': '1 3', '19w14b': '1 3',
        '1.14': 'creative hard', '1.20.4': 'creative hard', '26.3': 'creative hard', '': 'creative hard'
    };
    for (const [version, expected] of Object.entries(cases)) {
        const dir = tempDir(t);
        writeServerProperties(dir, { gamemode: 'creative', difficulty: 'hard' }, { version });
        assert.equal(modes(dir), expected, `new file on ${version || 'no version'}`);
    }

    const dir = tempDir(t);
    writeServerProperties(dir, {}, { version: '1.12.2' });
    assert.equal(modes(dir), '0 2', 'the defaults');

    write(dir, 'gamemode=survival\ndifficulty=easy\nmotd=A pack\n');
    writeServerProperties(dir, { gamemode: 'adventure', difficulty: 'peaceful' }, { mergeExisting: true, version: '1.12.2' });
    assert.equal(modes(dir), '2 0', 'merged into a pack\'s file');

    updateServerProperties(dir, { gamemode: 'spectator', difficulty: 'normal' }, { version: '1.7.10' });
    assert.equal(modes(dir), '3 2', 'an update given the version');
    updateServerProperties(dir, { gamemode: 'creative' });
    assert.equal(modes(dir), 'creative 2', 'an update not given one writes what it\'s given');
});

test('modeNameOf reads either form as the name', () => {
    assert.equal(modeNameOf('difficulty', '2'), 'normal');
    assert.equal(modeNameOf('difficulty', ' 0 '), 'peaceful');
    assert.equal(modeNameOf('gamemode', '3'), 'spectator');
    assert.equal(modeNameOf('gamemode', 'creative'), 'creative');
    assert.equal(modeNameOf('gamemode', '7'), '7');
    assert.equal(modeNameOf('motd', '1'), '1');
});

test('writeEula accepts the EULA', (t) => {
    const dir = tempDir(t);
    writeEula(dir);
    const content = fs.readFileSync(path.join(dir, 'eula.txt'), 'utf8');
    assert.match(content, /^eula=true$/m);
    assert.match(content, /^#.*aka\.ms\/MinecraftEULA/m);
});

// The Properties page shows PROPERTY_META's defaults; a new server gets
// DEFAULT_PROPERTIES. A default changed in one and not the other shows the
// user a "default" the server never had.
test('the Properties page defaults agree with a new server', () => {
    const disagree = [];
    for (const [key, value] of Object.entries(DEFAULT_PROPERTIES)) {
        const meta = PROPERTY_META[key];
        if (meta && String(meta.default) !== String(value)) disagree.push(`${key}: ${value} vs ${meta.default}`);
    }
    assert.deepEqual(disagree, []);
});

test('every Properties page default is valid for its own field', () => {
    const invalid = [];
    for (const [key, meta] of Object.entries(PROPERTY_META)) {
        if (meta.type === 'enum' && !meta.options.some((o) => o.value === meta.default)) invalid.push(key);
        if (meta.type === 'boolean' && !['true', 'false'].includes(meta.default)) invalid.push(key);
        if (meta.type === 'number') {
            const n = Number(meta.default);
            if (!Number.isFinite(n) || n < meta.min || n > meta.max) invalid.push(key);
        }
    }
    assert.deepEqual(invalid, []);
});
